database:
  username: root
  password: experion%40123
  host: localhost
  port: 3306
  name: zomato_db

files:
  input_csv: ..\data\output\restaurant_data_with_lat_long_46000.csv
  output_csv: ..\data\output\restaurant_data_with_lat_long_46000_updated_ETL_Pipeline.csv
