database:
  username: root
  password: experion%40123
  host: localhost
  port: 3306
  name: zomato_db

files:
  input_csv: ..\data\output\restaurant_data_with_lat_long_46000.csv
  output_csv: ..\data\output\restaurant_data_with_lat_long_46000_updated_ETL_Pipeline.csv

params:
  dimension_table_1: restaurant_dim_table
  dimension_table_2: location_dim_table
  fact_table_1: fact_table
  dimension_table_1_columns: ['NAME', 'CUSINE_CATEGORY', 'CUSINETYPE', 'TIMING', 'RATING_TYPE']
  dimension_table_2_columns: ['REGION', 'Latitude', 'Longitude', 'CITY']
  fact_table_1_columns: ['RATING', 'VOTES', 'PRICE']

